on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: '15 3 1 * *'  # <https://crontab.guru/#45_16_*_*_0> 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: ./run_tests.sh
